# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import preico.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'base_manager_name': '_plain_manager',
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PublicationTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('caption', models.CharField(max_length=512)),
                ('full_url', models.URLField()),
                ('cover_image', models.ImageField(upload_to='landing/publictions', validators=[preico.validators.ImageMinSizeValidator(min_height=150, min_width=270)])),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='landing.Publication')),
            ],
            options={
                'db_table': 'landing_publication_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'managed': True,
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='publicationtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
