# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import landing.models
import preico.validators


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='published',
        ),
        migrations.AddField(
            model_name='publicationtranslation',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicationtranslation',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=landing.models.Publication.__get_cover_image_path__, validators=[preico.validators.ImageMinSizeValidator(min_height=150, min_width=270)]),
        ),
    ]
