# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_lead_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_receive_updates',
            field=models.BooleanField(default=True),
        ),
    ]
