# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_lead_is_receive_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembertranslation',
            name='full_name',
            field=models.CharField(max_length=64),
        ),
    ]
