# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 22:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('txn_id', models.CharField(editable=False, max_length=256)),
                ('amount', models.FloatField(editable=False)),
                ('currency', models.CharField(editable=False, max_length=5)),
                ('address', models.CharField(editable=False, max_length=256)),
                ('timeout', models.IntegerField(editable=False)),
                ('status_url', models.URLField(editable=False)),
                ('qrcode_url', models.URLField(editable=False)),
                ('confirms_needed', models.IntegerField(editable=False)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
