# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0004_auto_20171222_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_amount_reserved',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
