# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0006_auto_20180104_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_balance',
            field=models.CharField(blank=True, max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='token_balance_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
