# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 07:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_lead_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cp', '0007_auto_20180111_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaTester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ios', models.BooleanField()),
                ('is_android', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('lead', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact', to='landing.Lead')),
                ('tester', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beta_tester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
