# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0008_betatester'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_token_balance',
            field=models.CharField(blank=True, max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
