# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 01:54
from __future__ import unicode_literals

import cp.models
from django.db import migrations, models
from django.apps import apps


def copy_wallet_as_referral_code(*args, **kwargs):
    Profile = apps.get_model('cp', 'Profile')

    profiles = Profile.objects.all()

    for profile in profiles:
        if profile.wallet:
            profile.referral_code = profile.wallet
        else:
            profile.referral_code = cp.models.generate_referral_code()

        profile.save()


def dummy_fn(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0009_auto_20180201_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(max_length=42, null=True, blank=True),
        ),
        migrations.RunPython(copy_wallet_as_referral_code, reverse_code=dummy_fn)
    ]
