# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 02:30
from __future__ import unicode_literals

import cp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0010_profile_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default=cp.models.generate_referral_code, max_length=42),
        ),
    ]
